apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - network-policies.yaml
  - kyverno-policies.yaml
  - tls.yaml
  - gateway.yaml
  - observability.yaml
